list.tsv

网络与新媒体 | 云南省 | 云南大学 | 新闻学院 | 181013136 | http://zsb.ynu.edu.cn/info/1014/1554.htm |  
-- | -- | -- | -- | -- | -- | --

找到一个新学校，请求合并

---

list.tsv

添加了一个有网络与新媒体专业的学校

---

list.tsv

Happy New year

---

list.tsv

Reverts hanteng/China_newmedia_undergrad#18

Revert "新增一个含有网络与新媒体专业的大学，请求合并"

---

list.tsv

专业：网络与新媒体
地区：山东省
学校：北京电影学院现代创意媒体学院
所在学院：传媒管理系
贡献者学号：162015240
URL：http://www.bfamcmc.edu.cn/info/1063/8905.htm

新添加：北京电影学院现代创意媒体学院，望采纳

---

list.tsv
php

网络与新媒体	湖南省	湖南师范大学	新闻与传播学院	172017144	http://xwxy.hunnu.edu.cn/showart.asp?id=1046

增加一所拥有网络与新媒体的学校，请求合并。

---

list.tsv

Reverts hanteng/China_newmedia_undergrad#75
不好意思，你的.tsv格式有误，由于我的失误将你merge，所以现在要回退，很抱歉。请你修改错误的.tsv格式再发起pr，谢谢。

Revert "添加一个有网络与新媒体的新学校"

---

list.tsv

陕西省安康学院，其学院为文学与传媒学院，已检查.tsv格式格式格式格式正确，请求合并，谢谢

新提交一个与原列表未重复、有网络与新媒体专业的学校（陕西省安康学院），请求合并，谢谢

---

list.tsv

你好，因之前不小心删掉上一个学校的pr，现在重新发起新的pr，请求合并，抱歉增加你的工作量了，谢谢

你好，因之前不小心删掉上一个学校的pr，现在重新发起新的pr，请求合并，谢谢

---

list.tsv

找到一个新的设有网络与新媒体专业的学校，请求合并，谢谢

---

list.tsv

您好，找到一所拥有网络与新媒体专业的学校，名为浙江越秀外国语学院。请查看。

您好，找到一所拥有网络与新媒体专业的学校，名为浙江越秀外国语学院。已检查内容格式，请求合并。

---

list.tsv

- 学校：红河学院
- 网新专业所属：人文学院
**已检查url、tsv格式，确保正确，希望采纳**

你好，我新添加红河学院人文学院网新专业，希望予以采纳，谢谢！

---

list.tsv

新增重庆工商大学融智学院，已检查.tsv格式正确，省份及URL无误，请求合并，谢谢你！

新增重庆工商大学融智学院

---

list.tsv

您好，我找到一个新的数据，网络与新媒体专业的学校:中国传媒大学南广学院，已检查.tsv格式正确，URL及省份均正确，请求添加合并，望采纳，谢谢。

新增数据：中国传媒大学南广学院,望采纳。

---

list.tsv

新添加了一个含有网络与新媒体专业的西南政法大学，已检查tsv格式确保正确，请求合并，谢谢

新添加了一个含有网络与新媒体专业的西南政法大学，请求合并，谢谢

---

list.tsv

 原安庆师范大学URL有误，现已修改，请求合并。

---

list.tsv

您好，这是我新找到的一间有网络与新媒体专业的学校，请求合并。谢谢！

---

list.tsv

新找到一个网络与新媒体的学校，辽宁师范大学海华学院，请求采纳，谢谢！

新找到一个网络与新媒体的学校，辽宁师范大学海华学院，请求采纳，谢谢！

---

list.tsv

你好！现提交 厦门华厦学院，人文学院，请求合并！谢谢

---

list.tsv

再次提出申请一间有网络与新媒体专业的学校（湖南理工学院)，已修改之前的错误，已检查tsv格式，确保正确，请求合并，谢谢

新添湖南理工学院的网络与新媒体专业

---

list.tsv

网络与新媒体	陕西省	西安交通大学	新闻与新媒体学院	172017487	http://xmtxy.xjtu.edu.cn/xygk/xyjj.htm
网络与新媒体	福建省	闽江学院	新闻传播学院	999999999	http://sjc.mju.edu.cn/nl/s/10.html
网络与新媒体	河北省	河北工业大学	新闻与传播学院	172018051	http://xwxy.haut.edu.cn/info/1019/2229.htm
网络与新媒体	江苏省	南京晓庄学院	新闻传播学院	181013062	http://xcy.njxzc.edu.cn/1167/list.htm
网络与新媒体	宁夏回族自治区	中国矿业大学银川学院	人文社科系	181013105	http://rwx.cumtyc.com.cn/zhuanyejieshao6/2016-06-01/92.html
网络与新媒体	广东省	东莞理工城市学院	文学与传媒学院	181013122	http://zjc.ccdgut.edu.cn/index.php/Home/New/page/cate_id/4/order/14/id/150
网络与新媒体	湖北省	汉口学院	传媒学院	181013038	http://cmxy.hkxy.edu.cn/#/95/105
网络与新媒体	黑龙江省	佳木斯大学	商学院	181013113	http://sxy.jmsu.edu.cn/info/1124/2245.htm
网络与新媒体	陕西省	西安科技大学高新学院	新传媒与经济管理学院	181013060	http://jg.gaoxinedu.com/zj/2018/0614/11449.html
网络与新媒体	陕西省	安康学院	文学与传媒学院	181013051 …

提交一个网新专业学校广东金融学院，请求合并，谢谢

---

list.tsv

新增云南民族大学，已检查tsv格式，请求合并，谢谢！！！！！！！！！！！！！！！！！！！！！！

新增云南民族大学，已检查tsv格式，请求合并，谢谢！！！！！！！！！！！！！！！！！！！！！！

---

list.tsv

新增添一个学校（平顶山学校），已检查tsv格式，请求合并，谢谢！

新增添一个学校（平顶山学校），已检查tsv格式，请求合并，谢谢！

---

list.tsv

一个有网络与新媒体专业的学校（陕西师范大学）

---

list.tsv

网络与新媒体	广西壮族自治区	广西师范大学	文学院	181013097	http://www.cllc.gxnu.edu.cn/2016/0619/c288a3260/page.htm

你好，新增一个网新学校，请求合并，谢谢！

---

list.tsv

新增贵州民族大学人文科技学院，请求合并，已经检查格式，与URL，谢谢！

新增贵州民族大学人文科技学院，请求合并，已经检查格式，与URL，谢谢！

---

list.tsv

新增一所黑龙江工程学院，请求合并，已检查URL和tsv格式，谢谢！

新增一所黑龙江工程学院，请求合并，已检查URL和tsv格式，谢谢！

---

list.tsv

Reverts hanteng/China_newmedia_undergrad#419
多了兩筆不必要數據

PR #419 操作錯誤 Revert "新添加了鞍山师范学院，请求合并。"

---

list.tsv

更新（深圳大学，传播学院，网络与新媒体专业）并提交合并。抱歉增加你的工作量。谢谢。

更新（深圳大学，传播学院，网络与新媒体专业）并提交合并。抱歉增加你的工作量。谢谢。

---

list.tsv

新增东华理工大学长江学院，已检查URL和tsv请求合并，谢谢

新增东华理工大学长江学院，已检查tsv和url，请求合并谢谢

---

list.tsv

新增一个有网络与新媒体的大学（安徽大学）

---

list.tsv

重新提交新学校：铜陵学院 含有网络与新媒体专业 请求合并 谢谢！

---

list.tsv

提交一个有网络与新媒体专业的学校（湖北理工学院），已检查tsv格式和url，望采纳，谢谢

提交一个有网络与新媒体专业的学校（湖北理工学院），已检查tsv格式和url，望采纳，谢谢
